### ISSUE TITLE
Suggestion: About the figma design

### ISSUE THREAD

**Issue by Mekin-jema** [Mekin-jema/GitHub_Action_Fundamental#1]
About the figma design ,  i think the design not fit to the  web , i assume the distance of my screen as the design , what i want to say is  i keep everything as it is except the width of the component ,i just fix the padding and margin related.....

**Comment by Mekin-jema** [comment]
```css
 it should be like this 
 body{
text:white;
background-color: green;
}

```
